# Generated by Django 3.1.7 on 2021-06-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='code',
            field=models.CharField(default='132', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
