# Generated by Django 3.1.7 on 2021-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='account/images'),
            preserve_default=False,
        ),
    ]
