# Generated by Django 3.1.7 on 2021-04-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210421_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates wether the user be treated as active user', verbose_name='Active'),
        ),
    ]
